### ISSUE TITLE
Add YAML support via circe-yaml

### ISSUE THREAD

**Issue by sbrunk** [vlovgr/ciris#480]
I have some YAML that I need to load into a configuration (via ciris-kubernetes). I had a brief look into what's needed to get this working with [circe-yaml](https://github.com/circe/circe-yaml).

Amazingly, all it took to get this working was to add the circe-yaml dependency, and replace the parser.
https://github.com/vlovgr/ciris/blob/b34af51bde89fea687e7d17a3a51c5db5885e5e9/modules/circe/src/main/scala/ciris/circe/circe.scala#L12

```diff
- import io.circe.parser.parse
+ import io.circe.yaml.parser.parse
```

It just works because the `parse` method in `circe-yaml` has the same signature as the circe json parser:
```scala
def parse(yaml: String): Either[ParsingFailure, Json]
```

So perhaps we can extend `def circeConfigDecoder` to take a `parser` (or delegate that to a private method) and then add a yaml module that uses the `circe-yaml` parser instead of the json parser.

Happy to draft a PR if you're interested.

**Comment by vlovgr** [comment]
Sounds great @sbrunk! Feel free to open a draft pull request.
