### ISSUE TITLE
Add contributing guide to microsite

### ISSUE THREAD

**Issue by vlovgr** [vlovgr/ciris#51]
The current [contributing guide](https://github.com/vlovgr/ciris/blob/master/contributing.md) only exists as a markdown document in the repository root. It would be a nice addition if this document moved to the `docs` project, and got it's own page on the microsite. We could still generate the document for the repository root, similar to how we [generate the readme](https://github.com/vlovgr/ciris/blob/8eb3408050ab5a782f2a872734a18d200b863e37/build.sbt#L330-L341).

**Comment by mericano1** [comment]
would you prefer to move the `contributing.md` to the `docs` folder and then copy it across with an sbt task (keeping it consistent with the readme) the other way round (leave it where it is and add it to the `docs`?)

**Comment by vlovgr** [comment]
I think we should have it as page in the microsite and copy it to `contributing.md`, similar to have we do for the readme (`sbt updateReadme`).
