### ISSUE TITLE
Build functionality for credstash as a configuration source

### ISSUE THREAD

**Issue by laurence-bird** [vlovgr/ciris#53]
Extending Ciris to include a ConfigSource, for loading secrets using credstash (https://github.com/fugue/credstash)

**Comment by laurence-bird** [comment]
Created this as a separate artifact due to dependency on underlying CLI: https://github.com/ovotech/ciris-credstash

**Comment by vlovgr** [comment]
Awesome! 👍 When you feel it's ready, we can merge this:
https://github.com/vlovgr/ciris/pull/59
