### ISSUE TITLE
Scala.js support

### ISSUE THREAD

**Issue by kubukoz** [vlovgr/ciris#554]
Hi! Are there any blockers for enabling cross-building to Scala.js? We'd probably need some separate sources, but other than that do you see any potential issues, JVM dependencies etc.?

**Comment by vlovgr** [comment]
I see. Lambdas are an appealing argument for Scala.js support. As long as the build complexity doesn't get too bad (maybe it's gotten better in the past 2.5 years?), I'm definitely open to accepting a pull request with Scala.js support. :)

**Comment by vlovgr** [comment]
Scala.js support will be added as part of #607.

**Comment by vlovgr** [comment]
Closing this issue as [v3.0.0-RC1](https://github.com/vlovgr/ciris/releases/tag/v3.0.0-RC1) has been released with #607.

Please try the release and open new issues for any issues encountered.
