### ISSUE TITLE
Load from file

### ISSUE THREAD

**Issue by tacerus** [vlovgr/ciris#582]
Hi,

is it documented somewhere how to load and parse a local configuration file?

In the "Quick example" and "Configurations"  documentation sections I mostly find example snippets for environment variables - but maybe I am missing something.

Thank you!

**Comment by vlovgr** [comment]
Hi, it depends on what configuration file format you're using. There's [ciris-hocon](https://github.com/2m/ciris-hocon), but no other configuration file format support in ciris. Alternatively, you can use `ciris.file` to load the file contents and parse the file format on your own.

**Comment by tacerus** [comment]
Thank you for the quick reply!
I was mainly interested in HOCON! But I did not quite understand if I'm supposed to load my file using `java.io.File` in combination with `ConfigFactory.parseFile` or if there was some integrated logic to take care of that?
Apologies if it's a rookie question!

**Comment by vlovgr** [comment]
I'd suggest opening an issue with questions over at [ciris-hocon](https://github.com/2m/ciris-hocon). :)

**Comment by tacerus** [comment]
OK, thank you Viktor!
