### ISSUE TITLE
Add support for iron

### ISSUE THREAD

**Issue by wvandermerwe** [vlovgr/ciris#662]
Hi! Would you be interested in adding support for [iron](https://github.com/Iltotore/iron), in a similar way to the existing refined module? I haven't looked into it yet, but would be happy to and submit a draft if you don't have any objections?

**Comment by vlovgr** [comment]
Absolutely, feel free to open a pull request. 👍

**Comment by rparree** [comment]
i had a PR over at iron, that i am moving over here: https://github.com/Iltotore/iron/pulls

**Comment by wvandermerwe** [comment]
@vlovgr sure no problem, I got stuck on the same issue that @rparree mentions
