### ISSUE TITLE
application.conf - typesafe configuration as config loader

### ISSUE THREAD

**Issue by geoHeil** [vlovgr/ciris#71]
How can I use the `application.conf` in Typesafe configuration format (HOCON) as a config source for ciris?

**Comment by vlovgr** [comment]
Ciris is intended as an alternative to configuration files, and libraries like Typesafe Config. With that said, it would technically be possible, but I'd be curious about the use case -- could you explain further, please? Feel free to drop by the [Gitter](https://gitter.im/vlovgr/ciris) channel to discuss.

**Comment by geoHeil** [comment]
Thanks, then I will go with pure config.

**Comment by 2m** [comment]
I seem to have also a use-case for this. I have an application written with Akka. Naturally all of the Akka configuration is done using typsafe-config library.

My application itself also has some configuration parameters. It is convenient to keep those in the same hocon files, especially if some parts are shared across my app and Akka.

Therefore I wrote a little library that implements HOCON configuration source for ciris. You can find it here: https://github.com/2m/ciris-hocon/

**Comment by vlovgr** [comment]
Thanks @2m! The ciris-hocon module looks great! I've included it in the list of [external libraries](https://cir.is/#external-libraries).
